### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: You must authenticate via a GitHub App.

### ISSUE THREAD

**Issue by elgohr** [synopsys-sig/detect-action#33]
Using a Github Personal Access Token the action responds with
```
Creating Black Duck Policy Check...
(node:1718) UnhandledPromiseRejectionWarning: HttpError: You must authenticate via a GitHub App.
    at /home/runner/work/_actions/synopsys-sig/detect-action/v0.3.2/webpack:/detect-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
For organisations that use dependencies from multiple private GitHub organisations this would mean to publish a GitHub App.
Private GitHub Apps can't be shared accross multiple GitHub organisations. This makes the action very impractical.

**Comment by nishwalshetty** [comment]
any workaround for this issue ?

**Comment by elgohr** [comment]
Looks like `github-token` is just used for communication with GitHub actions (for showing the report).
Configuring git to use a token is the solution.
